/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fresh;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CustomerSupport extends javax.swing.JFrame {

    File c = new File("C:\\programming\\Fresh");
    int ln;

    
    /**
     * Creates new form notepad
     */
    public CustomerSupport() {
        initComponents();
    }

    void createFolder(){
        if(!c.exists()){
            c.mkdirs();
        }
    }
    
    void readFile(){
        try {
            FileReader fr = new FileReader(c+"CustomerSupport.txt");
            System.out.println("file exists!");
        } catch (FileNotFoundException ex) {
            try {
                FileWriter fw = new FileWriter(c+"\\CustomerSupport.txt");
                System.out.println("File created");
            } catch (IOException ex1) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        
    }
    
    void addData(String Username, String Other){
        try {
            RandomAccessFile raf = new RandomAccessFile(c+"\\CustomerSupport.txt", "rw");
            for(int i=0;i<ln;i++){
                raf.readLine();
            }
            if(ln>0){
            raf.writeBytes("\r\n");
            raf.writeBytes("\r\n");
            }
            raf.writeBytes("Username:"+Username+ "\r\n");
            raf.writeBytes("Message:"+Other+ "\r\n");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
  
    void countLines(){
        try {
            ln=0;
            RandomAccessFile raf = new RandomAccessFile(c+"\\CustomerSupport.txt", "rw");
            for(int i=0;raf.readLine()!=null;i++){
                ln++;
            }
            System.out.println("number of lines:"+ln);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        other = new javax.swing.JLabel();
        sendBTN = new javax.swing.JButton();
        otherTF = new javax.swing.JScrollPane();
        tfother = new javax.swing.JTextArea();
        usr = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fresh: Pizza Delivery & More");
        setMinimumSize(new java.awt.Dimension(680, 520));
        getContentPane().setLayout(null);

        other.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        other.setForeground(new java.awt.Color(0, 102, 51));
        other.setText("Other");
        getContentPane().add(other);
        other.setBounds(60, 250, 50, 25);

        sendBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendBTN.setText("SEND");
        sendBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBTNActionPerformed(evt);
            }
        });
        getContentPane().add(sendBTN);
        sendBTN.setBounds(540, 440, 72, 23);

        otherTF.setBackground(new java.awt.Color(204, 204, 204));

        tfother.setBackground(new java.awt.Color(173, 142, 112));
        tfother.setColumns(20);
        tfother.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfother.setForeground(new java.awt.Color(255, 255, 204));
        tfother.setRows(5);
        tfother.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        tfother.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        otherTF.setViewportView(tfother);

        getContentPane().add(otherTF);
        otherTF.setBounds(60, 280, 550, 150);

        usr.setFont(new java.awt.Font("Segoe UI Black", 3, 22)); // NOI18N
        usr.setForeground(new java.awt.Color(0, 102, 51));
        usr.setText("Username");
        getContentPane().add(usr);
        usr.setBounds(58, 100, 140, 30);

        tfusername.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 51)));
        getContentPane().add(tfusername);
        tfusername.setBounds(400, 100, 210, 22);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.jpeg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 670, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBTNActionPerformed
        if (this.tfusername.getText().isEmpty() || 
                this.tfother.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, 
                    "Please enter all details");
        } else {
            createFolder(); 
            readFile();
            countLines();
            addData(tfusername.getText(),tfother.getText());  
            JOptionPane.showMessageDialog(null,"your message have been sent succesfully!");

        }
    }//GEN-LAST:event_sendBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerSupport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel other;
    private javax.swing.JScrollPane otherTF;
    private javax.swing.JButton sendBTN;
    private javax.swing.JTextArea tfother;
    private javax.swing.JTextField tfusername;
    private javax.swing.JLabel usr;
    // End of variables declaration//GEN-END:variables
}
