/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fresh;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {
    

    File f = new File("C:\\programming\\Fresh");
    int ln;  



    public Home() {
        initComponents();
    }

    void readFile(){
        try {
            FileReader fr = new FileReader(f+"\\logins.txt");
            System.out.println("file exists!");
        } catch (FileNotFoundException ex) {
            try {
                FileWriter fw = new FileWriter(f+"\\logins.txt");
                System.out.println("File created");
            } catch (IOException ex1) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        
    }
       
    void CheckData(String Username,String Password){
    
        try {
            RandomAccessFile raf = new RandomAccessFile(f+"\\logins.txt", "rw");
            String line = raf.readLine();
            Username=line.substring(9);
            Password=raf.readLine().substring(9);
            if(Username.equals(Username)& Password.equals(Password)){
                JOptionPane.showMessageDialog(null, "Password matched");
            }else{
                JOptionPane.showMessageDialog(null, "Wrong user/Password");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    void logic(String Username,String Password){
        try {
            RandomAccessFile raf = new RandomAccessFile(f+"\\logins.txt", "rw");
            for(int i=0;i<ln;i+=4){System.out.println("count "+i);
            
                String forUser = raf.readLine().substring(9);
                String forPswd = raf.readLine().substring(9);
                if(Username.equals(forUser) & Password.equals(forPswd)){
                    new OrderingFood().setVisible(true);
                    //JOptionPane.showMessageDialog(null, "password matched");
                    break;
                }else if(i==(ln-3)){
                    JOptionPane.showMessageDialog(null, "incorrect username/password");
                    break;
                }
                // if you are using user & passwword without email
                // then dont forget to replace  k<=2 with k=2 below
                for(int k=1;k<=2;k++){
                    raf.readLine();
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    void countLines(){
        try {
            ln=0;
            RandomAccessFile raf = new RandomAccessFile(f+"\\logins.txt", "rw");
            for(int i=0;raf.readLine()!=null;i++){
                ln++;
            }
            System.out.println("number of lines:"+ln);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBTN = new javax.swing.JButton();
        quote = new javax.swing.JLabel();
        usernameTXT = new javax.swing.JLabel();
        passwordTXT = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        signupBTN = new javax.swing.JButton();
        tfpassword = new javax.swing.JPasswordField();
        resetBTN = new javax.swing.JButton();
        quote2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fresh: Pizza Delivery & More");
        setMaximumSize(new java.awt.Dimension(710, 560));
        setMinimumSize(new java.awt.Dimension(710, 560));
        getContentPane().setLayout(null);

        loginBTN.setText("Login");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(loginBTN);
        loginBTN.setBounds(505, 310, 85, 40);

        quote.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        quote.setText("“Order your favorite pizza in a few minutes”");
        getContentPane().add(quote);
        quote.setBounds(220, 140, 300, 40);

        usernameTXT.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        usernameTXT.setForeground(new java.awt.Color(0, 102, 51));
        usernameTXT.setText("USERNAME");
        getContentPane().add(usernameTXT);
        usernameTXT.setBounds(160, 230, 120, 22);

        passwordTXT.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        passwordTXT.setForeground(new java.awt.Color(0, 102, 51));
        passwordTXT.setText("PASSWORD");
        getContentPane().add(passwordTXT);
        passwordTXT.setBounds(160, 280, 120, 22);

        tfusername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfusername.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 51)));
        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfusername);
        tfusername.setBounds(410, 230, 180, 22);

        signupBTN.setText("SIGN UP");
        signupBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBTNActionPerformed(evt);
            }
        });
        getContentPane().add(signupBTN);
        signupBTN.setBounds(505, 430, 85, 30);

        tfpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 51)));
        getContentPane().add(tfpassword);
        tfpassword.setBounds(410, 280, 180, 22);

        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });
        getContentPane().add(resetBTN);
        resetBTN.setBounds(410, 310, 85, 40);

        quote2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quote2.setText("Dont Have An Account?");
        getContentPane().add(quote2);
        quote2.setBounds(370, 440, 136, 16);

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-person-20.png"))); // NOI18N
        getContentPane().add(icon1);
        icon1.setBounds(140, 230, 20, 20);

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-lock-20.png"))); // NOI18N
        getContentPane().add(icon2);
        icon2.setBounds(140, 280, 20, 20);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rsz_icon.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(282, 24, 141, 114);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/background.jpeg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 700, 500);

        jMenu1.setText("Manage\n");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-info-25.png"))); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/icons8-customer-support-25.png"))); // NOI18N
        jMenuItem2.setText("Customer Support");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        if (this.tfusername.getText().isEmpty() || 
                this.tfpassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, 
                    "Please enter all details");
        }
        else {     
            readFile();
            countLines();
            logic(tfusername.getText(), tfpassword.getText());
        }
     
    }//GEN-LAST:event_loginBTNActionPerformed

    private void signupBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBTNActionPerformed
new SignUp().setVisible(true);
    }//GEN-LAST:event_signupBTNActionPerformed

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new AboutPage().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new CustomerSupport().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        tfusername.setText("");
        tfpassword.setText("");
    }//GEN-LAST:event_resetBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel passwordTXT;
    private javax.swing.JLabel quote;
    private javax.swing.JLabel quote2;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton signupBTN;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JTextField tfusername;
    private javax.swing.JLabel usernameTXT;
    // End of variables declaration//GEN-END:variables
}
